version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/crates/aggregator"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/core"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/integration_tests"
    schedule:
      interval: "daily"
