FROM rust:1.91-bookworm AS build

WORKDIR /root

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake libsasl2-dev protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN cargo build --release --bin graph_tally_escrow_manager

########################################################################################

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates libsasl2-dev openssl \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /root/target/release/graph_tally_escrow_manager /usr/local/bin/graph_tally_escrow_manager

ENTRYPOINT [ "/usr/local/bin/graph_tally_escrow_manager" ]
