FROM rust:1.91-bookworm AS build

WORKDIR /root

RUN apt-get update && apt-get install -y --no-install-recommends \
    librdkafka-dev libsasl2-dev pkg-config protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN cargo build --release --bin graph_tally_aggregator

########################################################################################

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates librdkafka1 libsasl2-2 openssl \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /root/target/release/graph_tally_aggregator /usr/local/bin/graph_tally_aggregator

ENTRYPOINT [ "/usr/local/bin/graph_tally_aggregator" ]
